name: Run_minLoRA_Tests

on: 
  push:
    branches:
      - i191656

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Python
        uses: actions/setup-python@v2
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Store paths of all python files in repo
        run: python get_python_file_paths.py
        
      - name: Install flake8
        run: pip install flake8
        
      - name: Run Flake8
        run: cat python_file_paths.txt | xargs flake8
      
      - name: Install black
        run: pip install black
        
      - name: Run black
        run: cat python_file_paths.txt | xargs python -m black
