name: "Security Analysis"

on:
  push:
    branches: 
      - i191861
   
jobs:
  codeQL_job:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        
      - name: Upload Results to Repo
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
